### ISSUE TITLE
Sviluppo agile vs Documentazione 

### ISSUE THREAD

**Issue by mmenapace** [iagosd/p1_demarchi_stefano#1]
Ho discusso con Narizzano la possiblità di avere requirement "dinamici" durante lo sviluppo del progetto.
La prima buona notizia è che non è un problema. Il punto è comprendere i requisiti ed esporli in maniera corretta e coerente.
Le eventuali modifiche successive non invalideranno quindi l'eventuale bontà dell'elaborato.
Più che uno sviluppo agile dovrete fare riferimento a uno sviluppo iterativo/incrementale.
Questo perchè la fase che stato affrontando (SRS, Diagram [..] ) non è proprio prevista dalle metodologie di sviluppo agili in senso stretto.

Ciao 
MM

**Comment by iagosd** [comment]
Grazie. Abbiamo finito la priva versione completa (sicuramente da rivedere), è aggiornata sul repository.
